### get all
GET http://localhost:8000/api/v1/users

### get all from vps
GET http://103.49.239.203:8000/api/v1/users

### get single
GET http://localhost:8000/api/v1/users/66b9bd83fd61a9da3436e9fe

### register
POST http://localhost:8000/api/v1/users/register
Content-Type: application/json

{
  "name": "dora dorami",
  "email": "dora@mail.com",
  "password": "iyainaja123"
}

### login 
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
  "email": "dora@mail.com",
  "password": "iyainaja123"
}

### login vps
GET http://103.49.239.203:8000/api/v1/users/login
Content-Type: application/json

{
  "email": "dora@mail.com",
  "password": "iyainaja123"
}

### logout
POST  http://localhost:8000/api/v1/users/logout

### delete 
 DELETE http://localhost:8000/api/v1/users/66b9bd83fd61a9da3436e9fe
